<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <AssemblyName>XamlPreviewer</AssemblyName>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <PlatformTarget>x64</PlatformTarget>
    <DisableFastUpToDateCheck>true</DisableFastUpToDateCheck>
  </PropertyGroup>

  <ItemGroup>
    <Resource Include="Resources\Icons\close.svg" />
    <Resource Include="Resources\Icons\expand-all.svg" />
    <Resource Include="Resources\Icons\find-next.svg" />
    <Resource Include="Resources\Icons\find-previous.svg" />
    <Resource Include="Resources\Icons\navigate-back.svg" />
    <Resource Include="Resources\Icons\navigate-forward.svg" />
    <Content Include="Resources\Cursors\*.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <Import Project="XamlPreviewer.WPF.targets" />
</Project>